### ISSUE TITLE
Support component style variations

### ISSUE THREAD

**Issue by hawkeyetwolf** [kalamuna/kalaponents#11]
### Tasks
- [x] Add a "style variation" _text_ field to the Kalaponent paragraphs bundle and add the field export code into `kalaponents.field.inc`.
- [x] Make a "multiple type" textarea variable to allow designers to specify class names with associated display name / description for the editor (replicate Classy Paragraphs behavior)
- [x] Hide the "styles" field from the back-end configuration field list via `kalaponents_get_available_fields()`.
- [x] Use States API to show/hide the styles field depending on whether a given component type has any styles defined.
- [x] In the paragraphs widget edit form in `kalaponents.module`, change the "style variations" field you created above from `text` to `select`. Don't give it any `#options` yet.
- [x] Attach javascript settings (using `#attach` instead of `drupal_add_js()`) that hold the list of style variations per component type.
- [ ] Attach javascript that adds a listener to the "component type" select list, so that when it is changed, we update the "style variations" select list options with the correct values.

**Comment by soniktrooth** [comment]
@derekderaps I had a try at implementing this the way that you originally wanted but it wasn't going to happen. Despite registering the widget as a text field, it was still being built with a select list via FAPI. Drupal won't let you change the option values on the page and then submit it back with options that it wasn't built with. The only way to achieve the result without ajaxifying the form would be to make the field a textfield, and then hide it and replace it with a dropdown in the js and sync the selected value back to the textfield. It would work but it's kinda ugly, especially if this is going to be contrib. 

Instead, I just ajaxified it for you in #17

**Comment by gremy** [comment]
@soniktrooth merged it cuz it looks good. And I am gonna test it good now and do fixes if needed.

**Comment by gremy** [comment]
Thank you @soniktrooth the AJAX changing of the Style variation is working, but there are some bugs.
* I get an error when I try to add another component
* I cannot save
I'll take it from here and attempt to fix these issues.

**Comment by soniktrooth** [comment]
@gremy that's weird—it was def working for me. I trust you can get it over the line though.

**Comment by hawkeyetwolf** [comment]
@soniktrooth @gremy, what's the status on this one?

**Comment by hawkeyetwolf** [comment]
D7 is legacy, closing out this issue for now.
